spring:
  application:
    name: sesim
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000  # 10분

jwt:
  secret-key: ${JWT_SECRET}
  expiration-time: 60000 # 1분(test)
  token-prefix: "Bearer "
  header-string: "Authorization"
  issuer: "sesim"
  refresh-expiration-time: 86400000
aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  saas:
    access-key: ${SAAS_AWS_ACCESS_KEY}
    secret-key: ${SAAS_AWS_SECRET_KEY}
  region: ap-northeast-2
  s3:
    setup-bucket: sesimbucket
    setup-zip-key: k3s-setup/v7.zip

# SSH 설정
ssh:
  connection-timeout: 60000
  channel-timeout: 30000